### ISSUE TITLE
Vertaisarviointi #1

### ISSUE THREAD

**Issue by MiikaMatias** [hy-tsoha/local-pg#3]
Ensinnäkin pahoittelut myöhäisestä arviosta!

Sovellus on edennyt mainiosti, ja toiminnassa ei ole vikaa. Monet peruspalikat ovat säädetty vaikka versiosta puuttuukin muutamia keskeisiä asioita; esim. vaikkapa prosentteja ei ole toistaiseksi laskettu. Tämä ei ole varsinaista kritiikkiä kylläkään; kaikki jo implementoidut toiminnot pelaavat kuten pitää. 
![image](https://github.com/hy-tsoha/local-pg/assets/100348027/a0dbcd06-997e-4ffa-9aef-a66dae530f1c)

Ihan siisteyden puolesta on tyypillistä siirtää lähdekoodi /src/ kansioon juuren alapuolelle. Mielestäni tämä on hyvä ja siisti tapa toimia, jotta mahdollinen dokumentaatio ja muut toiminnan kannalta vähemmän relevantit tiedostot eivät häiritse käyttäjää tai koodin lukijaa. 

En myöskään jättäisi testdata.sql tai schema.sql tiedostoihin kömpelösti oman järjestelmäsi polkuja. Eikö esim tasks tyyppisellä ratkaisulla voisi tehdä järjestelmällä kuin järjestelmällä toimivan database setup höskän? Uskoisin että tähän on monia tapoja toimia jotka eivät edellytä että käyttäjä manuaalisesti copypasteaa nuo tuonne.

Tietokannan suunnittelu on mielestäni toteutettu hyvin. 
HTML templatet ovat asianmukaisesti tehty ja toimivat hyvin. 
Tietokannan manipulointi on monipuolista. 
Toiminnallisuuden segrekointi on toistaiseksi mielekästä. 
Myös kyselyt vaikuttavat olevan turvallisesti toteutettuja. Esim. injektiot otettu huomioon. 

Mainittakoon vielä että sovelluksen idea on siisti!

**Comment by qzuw** [comment]
Hei,

tämä issue on tainnut tulla väärään repoon. Suljen koska ei liity pg:n asennusskriptiin.

Tämä jää kuitenkin tänne suljettuihin issueihin, joten voit tarvittaessa copypasteta oikeaan repoon. Jos vertaisarviointien dl meni jo, linkittämällä suljettuun issueen voit osoittaa että teit arvioinnin (vaikkakin väärään paikkaan).
